export const GET_ERRORS = "GET_ERRORS";
export const GET_MEDICINES = "GET_MEDICINES";
export const GET_MEDICINE = "GET_MEDICINE";
export const DELETE_MEDICINE = "DELETE_MEDICINE";

export const SET_CURRENT_USER = "SET_CURRENT_USER";
